const {createClient}=supabase;
const sb=createClient(SILAI_CONFIG.supabaseUrl,SILAI_CONFIG.supabaseKey);
let user=null,customers=[],sewing=[];
const root=document.getElementById('root');
function intro(){root.innerHTML=`<div class="splash"><div class="splashCard"><img class="splashLogo" src="icon.svg"><div class="splashLine"></div><h1 class="splashBrand">Silai Diary</h1><div class="splashSub">Tailor Manager</div><div class="splashTag">તમારું માપ • તમારી સિલાઈ • તમારો હિસાબ</div></div><div class="splashPowered">Powered by <b>SMJ Group</b></div></div>`}

const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const monthKey=d=>String(d).slice(0,7);
const yearKey=d=>String(d).slice(0,4);
const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString('gu-IN',{day:'2-digit',month:'short',year:'numeric'});
const monthName=ym=>{const [y,m]=ym.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleDateString('gu-IN',{month:'long',year:'numeric'})};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function login(){root.innerHTML=`<div class="login"><div class="loginbox"><img class="logo" src="icon.svg"><div style="text-align:center"><span class="loginBadge">TAILOR MANAGEMENT APP</span></div><h1 class="loginTitle" style="text-align:center;color:var(--navy);margin:0">Silai Diary</h1><p class="loginSub">સાચું માપ • સાચી સિલાઈ • સરળ હિસાબ</p><div id="loginform"><div class="field inputIcon"><label>Email ID</label><span>✉</span><input id="email" type="email" placeholder="તમારી Email ID"></div><div class="field"><label>Email ID</label><input id="email" type="email" placeholder="તમારી Email ID"></div><div class="field inputIcon"><label>Password</label><span>🔒</span><input id="pass" type="password" placeholder="Password"></div><button class="btn primary" style="width:100%" onclick="doLogin()">Login</button><button class="btn light" style="width:100%;margin-top:8px" onclick="forgot()">Forgot Password?</button><button class="btn gold" style="width:100%;margin-top:8px" onclick="signup()">Create New Account</button></div><div class="footer">Powered by SMJ Group</div></div></div>`}
async function doLogin(){const email=document.getElementById('email').value.trim(),password=document.getElementById('pass').value;if(!email||!password)return toast('Email અને Password લખો');const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);await start()}
async function signup(){const email=document.getElementById('email').value.trim(),password=document.getElementById('pass').value;if(!email||password.length<6)return toast('Email અને 6+ અક્ષરનો Password આપો');const {error}=await sb.auth.signUp({email,password});if(error)return toast(error.message);toast('Account બન્યું. Email verification જરૂરી હોઈ શકે.')}
async function forgot(){const email=document.getElementById('email').value.trim();if(!email)return toast('પહેલા Email લખો');const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.href});toast(error?error.message:'Password reset email મોકલ્યો છે')}
async function start(){const s=await sb.auth.getSession();user=s.data.session?.user;if(!user)return login();await load();home()}
async function load(){let c=await sb.from('tailor_customers').select('*').order('name');if(c.error)toast(c.error.message);customers=c.data||[];let e=await sb.from('tailor_sewing_entries').select('*').order('sewing_date',{ascending:false});if(e.error)toast(e.error.message);sewing=e.data||[]}
function shell(title,body,active='home'){root.innerHTML=`<div class="app"><div class="top"><div class="toprow"><div class="brand"><img src="icon.svg"><div><h1>Silai Diary</h1><small>Tailor Manager</small></div></div><button class="iconbtn" onclick="signout()">⇥</button></div><div style="margin-top:8px;font-size:13px;opacity:.85">${esc(title)}</div></div><main class="content">${body}</main><nav class="bottom"><button onclick="home()" class="${active==='home'?'active':''}"><span>⌂</span>હોમ</button><button onclick="customerList()" class="${active==='customers'?'active':''}"><span>👤</span>ગ્રાહકો</button><button onclick="sewingPage()" class="${active==='sewing'?'active':''}"><span>✂</span>સિલાઈ</button><button onclick="reportPage()" class="${active==='report'?'active':''}"><span>▥</span>રિપોર્ટ</button></nav></div>`}
function totals(){const t=today(),m=t.slice(0,7),y=t.slice(0,4);return{today:sewing.filter(x=>x.sewing_date===t).reduce((a,x)=>a+x.pairs,0),month:sewing.filter(x=>x.sewing_date.startsWith(m)).reduce((a,x)=>a+x.pairs,0),year:sewing.filter(x=>x.sewing_date.startsWith(y)).reduce((a,x)=>a+x.pairs,0),total:sewing.reduce((a,x)=>a+x.pairs,0)}}
function home(){const n=totals();shell('ડેશબોર્ડ',`<div class="grid"><div class="stat"><b>${customers.length}</b><span>કુલ ગ્રાહક</span></div><div class="stat"><b>${n.today}</b><span>આજની સિલાઈ</span></div><div class="stat"><b>${n.month}</b><span>આ મહિનાની સિલાઈ</span></div><div class="stat"><b>${n.total}</b><span>કુલ સિલાઈ</span></div></div><div class="actions"><button class="btn primary" onclick="newCustomer()">＋ નવો ગ્રાહક</button><button class="btn gold" onclick="sewingPage()">✂ સિલાઈ ઉમેરો</button><button class="btn green" onclick="dailyReportPage()">📅 રોજનો રિપોર્ટ</button><button class="btn light" onclick="reportPage()">📊 રિપોર્ટ</button></div><div class="card"><h3>આજનો હિસાબ</h3><div class="row"><span>${fmt(today())}</span><span class="pill">${n.today} જોડી</span></div><button class="btn light" style="width:100%;margin-top:10px" onclick="dailyReportPage()">આજની સંપૂર્ણ વિગત જુઓ →</button></div><div class="card"><h3>મહિનાનો WhatsApp રિપોર્ટ</h3><div class="row"><span>${monthName(monthKey(today()))}</span><span class="pill">${n.month} જોડી</span></div><button class="btn green" style="width:100%;margin-top:10px" onclick="whatsappMonthly()">WhatsApp પર રિપોર્ટ મોકલો</button></div><div class="card"><h3>તમારો Cloud Backup</h3><div class="row"><span style="font-size:13px">${esc(user.email)}</span><span class="pill">Synced</span></div></div>`)}
function newCustomer(){shell('નવો ગ્રાહક',`<div class="card"><h2>ગ્રાહકની વિગતો</h2><div class="field"><label>ગ્રાહકનું નામ *</label><input id="cname" placeholder="નામ દાખલ કરો"></div><div class="field"><label>મોબાઇલ નંબર</label><input id="cmobile" inputmode="tel" placeholder="મોબાઇલ નંબર"></div><div class="field"><label>ગામ</label><input id="cvillage" placeholder="ગામનું નામ"></div><button class="btn primary" style="width:100%" onclick="saveCustomer()">સેવ કરો →</button></div>`,'customers')}
async function saveCustomer(){const name=document.getElementById('cname').value.trim();if(!name)return toast('ગ્રાહકનું નામ જરૂરી છે');const {data,error}=await sb.from('tailor_customers').insert({user_id:user.id,name,mobile:document.getElementById('cmobile').value.trim(),village:document.getElementById('cvillage').value.trim()}).select().single();if(error)return toast(error.message);customers.push(data);measurementPage(data.id)}
function customerList(){let list=customers.map(c=>`<div class="customer"><div><b>${esc(c.name)}</b><small>${esc(c.mobile||'')} • ${esc(c.village||'')}</small></div><button class="btn light" onclick="measurementPage('${c.id}')">માપ</button></div>`).join('');shell('ગ્રાહકોની યાદી',`<button class="btn primary" style="width:100%" onclick="newCustomer()">＋ નવો ગ્રાહક</button><div class="card"><div class="field"><input id="search" placeholder="ગ્રાહક શોધો..." oninput="filterCustomers()"></div><div id="clist">${list||'<div class="empty">હજુ કોઈ ગ્રાહક નથી.</div>'}</div></div>`,'customers')}
function filterCustomers(){const q=document.getElementById('search').value.toLowerCase();document.getElementById('clist').innerHTML=customers.filter(c=>(c.name+' '+c.mobile+' '+c.village).toLowerCase().includes(q)).map(c=>`<div class="customer"><div><b>${esc(c.name)}</b><small>${esc(c.mobile||'')} • ${esc(c.village||'')}</small></div><button class="btn light" onclick="measurementPage('${c.id}')">માપ</button></div>`).join('')||'<div class="empty">ગ્રાહક મળ્યો નથી.</div>'}
const fields=[['shirt_length','લંબાઈ'],['chest','છાતી'],['shoulder','શોલ્ડર'],['bay','બાય'],['collar','કોલર'],['cuff','કફ'],['pant_length','લંબાઈ'],['waist','કમર'],['seat','સીટ'],['sathod','સાથોડ'],['dichan','ડિચણ'],['mori','મોરી'],['khacho','ખાચો']];
async function measurementPage(cid){const c=customers.find(x=>x.id===cid);if(!c)return customerList();const r=await sb.from('tailor_measurements').select('*').eq('customer_id',cid).order('created_at',{ascending:false}).limit(1);renderMeasurement(c,r.data?.[0]||{})}
function renderMeasurement(c,ms){const shirt=fields.slice(0,6),pant=fields.slice(6);shell('માપ લો',`<div class="card"><div class="row"><div><h2>${esc(c.name)}</h2><small>${esc(c.mobile||'')} • ${esc(c.village||'')}</small></div><span class="pill">માપ</span></div></div><div class="card"><div class="tabs"><button id="st" class="on" onclick="showMeasure('shirt')">શર્ટ & જુબ્બા</button><button id="pt" onclick="showMeasure('pant')">પેન્ટ & લેંઘા</button></div><div id="shirtFields">${shirt.map(([k,l])=>`<div class="field"><label>${l}</label><input id="m_${k}" value="${ms[k]??''}" inputmode="decimal"></div>`).join('')}</div><div id="pantFields" class="hidden">${pant.map(([k,l])=>`<div class="field"><label>${l}</label><input id="m_${k}" value="${ms[k]??''}" inputmode="decimal"></div>`).join('')}</div><button class="btn primary" style="width:100%" onclick="saveMeasurement('${c.id}')">માપ સેવ કરો</button></div><div class="card"><h3>સિલાઈ ઉમેરો</h3><div class="twocol"><div class="field"><label>જોડી</label><input id="pairs" type="number" min="1" value="1"></div><div class="field"><label>તારીખ</label><input id="sdate" type="date" value="${today()}"></div></div><button class="btn gold" style="width:100%" onclick="addSewing('${c.id}')">＋ સિલાઈ ઉમેરો</button></div>`,'customers')}
function showMeasure(x){document.getElementById('shirtFields').classList.toggle('hidden',x!=='shirt');document.getElementById('pantFields').classList.toggle('hidden',x!=='pant');document.getElementById('st').classList.toggle('on',x==='shirt');document.getElementById('pt').classList.toggle('on',x==='pant')}
async function saveMeasurement(cid){const o={user_id:user.id,customer_id:cid};fields.forEach(([k])=>{const v=document.getElementById('m_'+k)?.value.trim();o[k]=v?Number(v):null});const {error}=await sb.from('tailor_measurements').insert(o);if(error)return toast(error.message);toast('માપ સેવ થઈ ગયું')}
async function addSewing(cid){const pairs=Number(document.getElementById('pairs').value),date=document.getElementById('sdate').value;if(!pairs||pairs<1)return toast('જોડીની સંખ્યા આપો');const {data,error}=await sb.from('tailor_sewing_entries').insert({user_id:user.id,customer_id:cid,pairs,sewing_date:date}).select().single();if(error)return toast(error.message);sewing.unshift(data);toast(`${pairs} જોડી સિલાઈ ઉમેરાઈ ગઈ`);dailyReportPage(date)}
function sewingPage(){const t=today();const rows=sewing.filter(x=>x.sewing_date===t);const total=rows.reduce((a,x)=>a+x.pairs,0);let html=rows.map(x=>{const c=customers.find(c=>c.id===x.customer_id);return `<div class="customer"><div><b>${esc(c?.name||'Unknown')}</b><small>${esc(c?.village||'')} • ${fmt(x.sewing_date)}</small></div><span class="pill">${x.pairs} જોડી</span></div>`}).join('');shell('સિલાઈ હિસાબ',`<div class="card"><h3>આજની સિલાઈ</h3><div class="reportnum">${total} જોડી</div>${html||'<div class="empty">આજે હજુ સિલાઈ ઉમેરાઈ નથી.</div>'}</div><div class="card"><h3>ગ્રાહક પસંદ કરો</h3>${customers.map(c=>`<button class="btn light" style="width:100%;margin:4px 0;text-align:left" onclick="measurementPage('${c.id}')">👤 ${esc(c.name)} <small>${esc(c.village||'')}</small></button>`).join('')||'<div class="empty">પહેલા ગ્રાહક ઉમેરો.</div>'}</div>`,'sewing')}
function dailyReportPage(date=today()){const rows=sewing.filter(x=>x.sewing_date===date);const total=rows.reduce((a,x)=>a+x.pairs,0);let by={};rows.forEach(x=>by[x.customer_id]=(by[x.customer_id]||0)+x.pairs);const list=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([id,n])=>{const c=customers.find(c=>c.id===id);return `<div class="customer"><div><b>${esc(c?.name||'Unknown')}</b><small>${esc(c?.mobile||'')} • ${esc(c?.village||'')}</small></div><span class="pill">${n} જોડી</span></div>`}).join('');shell('રોજનો રિપોર્ટ',`<div class="card"><div class="field"><label>તારીખ પસંદ કરો</label><input id="reportDate" type="date" value="${date}" onchange="dailyReportPage(this.value)"></div><div class="row"><h2 style="margin:0">${fmt(date)}</h2><span class="pill">${total} જોડી</span></div></div><div class="card"><h3>આજની સંપૂર્ણ સિલાઈ</h3>${list||'<div class="empty">આ તારીખે કોઈ સિલાઈ નથી.</div>'}</div><button class="btn green" style="width:100%" onclick="whatsappDaily('${date}')">WhatsApp પર રોજનો રિપોર્ટ</button>`,'report')}
function reportPage(){const ym=monthKey(today()),y=yearKey(today()),n=totals();let by={};sewing.forEach(x=>by[x.customer_id]=(by[x.customer_id]||0)+x.pairs);let table=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([id,v])=>`<div class="customer"><div><b>${esc(customers.find(c=>c.id===id)?.name||'Unknown')}</b></div><span class="pill">${v} જોડી</span></div>`).join('');shell('સિલાઈ રિપોર્ટ',`<div class="grid"><div class="stat"><b>${n.today}</b><span>આજ</span></div><div class="stat"><b>${n.month}</b><span>આ મહિનો</span></div><div class="stat"><b>${n.year}</b><span>આ વર્ષ</span></div><div class="stat"><b>${n.total}</b><span>કુલ</span></div></div><div class="card"><h3>મહિનાનો રિપોર્ટ</h3><div class="row"><span>${monthName(ym)}</span><span class="pill">${n.month} જોડી</span></div><button class="btn green" style="width:100%;margin-top:10px" onclick="whatsappMonthly()">📲 WhatsApp પર મહિનાનો રિપોર્ટ</button></div><div class="card"><h3>ગ્રાહક પ્રમાણે કુલ સિલાઈ</h3>${table||'<div class="empty">હજુ કોઈ રેકોર્ડ નથી.</div>'}</div>`,'report')}
function monthlyData(ym){const rows=sewing.filter(x=>x.sewing_date.startsWith(ym));const total=rows.reduce((a,x)=>a+x.pairs,0);const by={};rows.forEach(x=>by[x.customer_id]=(by[x.customer_id]||0)+x.pairs);const daily={};rows.forEach(x=>daily[x.sewing_date]=(daily[x.sewing_date]||0)+x.pairs);return{rows,total,by,daily}}
function whatsappMonthly(ym=monthKey(today())){const d=monthlyData(ym);let text=`✂️ *Silai Diary – Tailor Report*\n\n📅 *મહિનો:* ${monthName(ym)}\n👕 *કુલ સિલાઈ:* ${d.total} જોડી\n👥 *ગ્રાહકો:* ${Object.keys(d.by).length}\n\n📌 *દિવસ પ્રમાણે:*\n`;Object.keys(d.daily).sort().forEach(k=>text+=`• ${fmt(k)} — ${d.daily[k]} જોડી\n`);text+='\n👤 *ગ્રાહક પ્રમાણે:*\n';Object.entries(d.by).sort((a,b)=>b[1]-a[1]).forEach(([id,n])=>{const c=customers.find(c=>c.id===id);text+=`• ${c?.name||'Unknown'} — ${n} જોડી\n`});text+='\n_Powered by SMJ Group_';window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')}
function whatsappDaily(date){const rows=sewing.filter(x=>x.sewing_date===date);const total=rows.reduce((a,x)=>a+x.pairs,0);let by={};rows.forEach(x=>by[x.customer_id]=(by[x.customer_id]||0)+x.pairs);let text=`✂️ *Silai Diary – Daily Report*\n\n📅 *તારીખ:* ${fmt(date)}\n👕 *કુલ સિલાઈ:* ${total} જોડી\n\n`;Object.entries(by).sort((a,b)=>b[1]-a[1]).forEach(([id,n])=>{const c=customers.find(c=>c.id===id);text+=`• ${c?.name||'Unknown'} — ${n} જોડી\n`});text+='\n_Powered by SMJ Group_';window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')}
async function signout(){await sb.auth.signOut();user=null;login()}
sb.auth.onAuthStateChange((e)=>{if(e==='SIGNED_OUT')login()});
intro();setTimeout(start,1800);
